import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./header"
import { Web3StateProvider } from "./lib/web3state";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "voting dApp",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Web3StateProvider>
          <Header />
        {children}
        </Web3StateProvider>
      </body>
    </html>
  );
}

